[package]
authors = ["Sean Bowe <sean@z.cash>"]
description = "Cryptographic library for Zcash Sapling"
documentation = "https://github.com/zcash-hackworks/sapling"
homepage = "https://github.com/zcash-hackworks/sapling"
license = "MIT/Apache-2.0"
name = "sapling-crypto"
repository = "https://github.com/zcash-hackworks/sapling"
version = "0.0.1"

[dependencies.pairing]
version = "~0.13.2"
features = ["expose-arith"]

[dependencies]
rand = "0.4"
blake2 = "0.7"
digest = "0.7"
bellman = "0.0.8"

byteorder = "1"

[dev-dependencies]
hex-literal = "0.1"

[features]
default = ["u128-support"]
u128-support = ["pairing/u128-support"]
